### PR TITLE
SwipeView in SwipeView support, support for other browsers, onClick handler.

### PR DESCRIPTION
**Pull request by mwidmann**
Ciao Matteo,

I've added a couple of things I needed while working with your great class. 
- transitions also for firefox, opera and ie
- similar to the `onFlip` handler I added a `onClick` handler to catch single taps on elements in a `SwipeView`. I tried by adding the click event to the object inside the `swipeview-masterpage-*` first, but found out it was triggered every time a swipe was performed as well.
- I introduced the global `active_SwipeView` to be able to nest `SwipeView`s in `SwipeView`s

I don't know if you want to merge the changes into master, just wanted to inform you about what I did.

Cheers,
Martin

### CODE REVIEW

**Comment by cubiq** [comment]
great job @mwidmann ! I'll review your changes in the coming days. I believe FF/Opera/IE support should be included but maybe we should selectively add vendor specific transitions

**Comment by mwidmann** [comment]
I changed the code to selectively use the vendor specific properties on the style object. The only portion I left all four of them is in the `handleEvent`switch where it doesn't hurt. 

I decided to create a `vendor`Object to hold the various vendor specific stuff. I use `document.body.style.VENDORTransform != undefined`to figure out whether or not the current browser supports this specific prefix. Not 100% sure if this is a safe way though.

**Comment by lukebennett** [comment]
@cubiq Did you decide against including these changes or have you not had time to review yet? Would be great to see onClick support get added.

**Comment by cubiq** [comment]
Yes, I'm willing to include them but I'd make multi-vendor support a little less "verbose". It's more of a coding style issue than a bug in the pushed code or something.

**Comment by lukebennett** [comment]
Is that based on @mwidmann's original pull request as your previous comment was, or the follow-up commit (85c2152) he supplied which made multi-vendor support less verbose? i.e. are you saying his follow-up commit doesn't go far enough and you'd prefer it to be less verbose still?

**Comment by cubiq** [comment]
Lines 15-45 I bet there's a better way :) just didn't have the time to figure it out. Thanks for the heads up anyway.

**Comment by xtreme-tanzeeb-khalili** [comment]
How about using [prefix-free](http://leaverou.github.com/prefixfree/)?

**Comment by cubiq** [comment]
I added full modern browsers compatibility. Please review/debug/comment thanks

**Pull request closed without merging**
