### PR TITLE
Crossbrowser transforms

### PR DESCRIPTION
**Pull request by simonratner**
Add support for css transforms in some other browsers, including graceful fallback to still fire the flip event in browsers without transitions (ie9).

Tested in chrome, firefox11, ie9; _not_ tested in opera.

### CODE REVIEW

**Comment by cubiq** [comment]
I have to double check it but I believe that the only way to support browsers without transition (or transitionEnd) is with a timeout (or with reqanimframe). basically the if ( !hasTransition ) might not be enough.

**Comment by simonratner** [comment]
Perhaps you are right, I am a javascript noob. This worked for me in ie9, but there are likely edge cases. (Actually now I am thinking movein/moveout is one, I should take a look and make sure those are still fired.)

I have no intention of replicating the functionality accurately in unsupported browsers; just enough to keep things functional and degrading more or less gracefully in terms of visuals.

**Comment by simonratner** [comment]
Added another commit to the pull request; this one simply guards add/remove/dispatchEvent calls to avoid breaking in ie7/8. Swiping obviously doesn't work, but the view is still rendered correctly and can be paginated with prev/next/gotoPage.

An additional caveat for ie7 is the lack of document.querySelector, but I chose not to fix that since it is easy to work around with existing code by passing an element instead of a selector.

Feel free to merge as much or as little of this as you see fit.

**Comment by gaoyanqi** [comment]
can't work on IE10,this.wrapper.clientWidth=0;

**Comment by gaoyanqi** [comment]
I add this code "if(this.wrapperWidth == 0) this.wrapperWidth = this.wrapper.scrollWidth;" in refreshSize method and remove -webkit- in css,change webkitTransitionEnd to transitionEnd event then It can work in IE 10.

**Comment by cubiq** [comment]
I added full modern browsers compatibility. Please review/debug/comment thanks

**Comment by ghost23** [comment]
Hi,
since IE9 has no transitions and as i understand you still rely on those, in IE9 SwipeView does not work for me correctly. For instance, the internal __flip() is never called, unless you directly use gotoPage().

And since __flip is not called, the event is not dispatched and thus my navigation cannot be updated to reflect the current state.

What to do?

**Pull request closed without merging**
